# Generated by Django 2.0.1 on 2018-01-11 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_student_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': '用户列表', 'verbose_name_plural': '用户列表'},
        ),
    ]
