# Generated by Django 2.0.1 on 2018-01-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='姓名')),
                ('age', models.SmallIntegerField(verbose_name='年龄')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('sex', models.SmallIntegerField(choices=[(1, '男'), (2, '女'), (3, '未知')], verbose_name='性别')),
            ],
            options={
                'verbose_name': '7*24',
                'verbose_name_plural': '快讯列表管理',
            },
        ),
    ]
