# Generated by Django 2.0.1 on 2018-01-11 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sev', '0002_auto_20180111_1958'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '分类', 'verbose_name_plural': '分类'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '标签', 'verbose_name_plural': '标签'},
        ),
    ]
