# Generated by Django 2.0.1 on 2018-01-11 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sev', '0003_auto_20180111_2050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': '发布文章', 'verbose_name_plural': '发布文章'},
        ),
    ]
